theme: jekyll-theme-cayman
Der Gutschein-Bot soll künftig Gutscheine suchen, testen und anzeigen.
Aktuell ist er noch in der Pre-Alpha-Phase und nicht funktionsfähig.
Es lohnt aber sich auf jeden Fall, vor dem Einkauf auf Bummelwelt.de nach einem gültigen Gutscheincode zu suchen, so einfach ist es, Geld zu sparen.
